-- MySQL Script generated by MySQL Workbench
-- 03/01/15 18:39:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wargame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wargame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wargame` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wargame` ;

-- -----------------------------------------------------
-- Table `wargame`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`player` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `player_name` VARCHAR(64) NOT NULL,
  `player_password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `player_name_UNIQUE` (`player_name` ASC),
  INDEX `player_password_INDEX` (`player_name` ASC, `player_password` ASC))
ENGINE = InnoDB
COMMENT = 'basic login info';


-- -----------------------------------------------------
-- Table `wargame`.`game_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`game_session` (
  `session_id` INT NOT NULL,
  `started_at` DATETIME NULL,
  `ended_at` DATETIME NULL,
  `won_by` INT NULL COMMENT 'NULL if draw, otherwise player_id',
  PRIMARY KEY (`session_id`),
  INDEX `fk_game_session_player_won_idx` (`won_by` ASC),
  CONSTRAINT `fk_game_session_player1`
    FOREIGN KEY (`won_by`)
    REFERENCES `wargame`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tracks game sessions';


-- -----------------------------------------------------
-- Table `wargame`.`player_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`player_session` (
  `player_session_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `joined_at` DATETIME NULL,
  `ended_at` DATETIME NULL,
  PRIMARY KEY (`player_session_id`),
  INDEX `fk_player_session_players1_idx` (`player_id` ASC),
  INDEX `fk_player_session_game_sessions1_idx` (`session_id` ASC),
  CONSTRAINT `fk_player_session_players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `wargame`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_session_game_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `wargame`.`game_session` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'link between player and game session';


-- -----------------------------------------------------
-- Table `wargame`.`round`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`round` (
  `round_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `won_by` INT NULL COMMENT 'NULL if draw, otherwise player_id',
  `started_at` DATETIME NULL DEFAULT NULL,
  `ended_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`round_id`),
  INDEX `fk_rounds_game_sessions1_idx` (`session_id` ASC),
  INDEX `fk_rounds_players1_idx` (`won_by` ASC),
  CONSTRAINT `fk_rounds_game_sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `wargame`.`game_session` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rounds_players1`
    FOREIGN KEY (`won_by`)
    REFERENCES `wargame`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wargame`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`card` (
  `card_id` INT NOT NULL,
  `card_name` VARCHAR(32) NOT NULL,
  `card_value` TINYINT UNSIGNED NOT NULL COMMENT '2-13',
  PRIMARY KEY (`card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wargame`.`cards_in_round`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`cards_in_round` (
  `card_round_id` INT NOT NULL AUTO_INCREMENT,
  `card_id` INT NOT NULL,
  `round_id` INT NOT NULL,
  `drawn_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'NULL',
  `drawn_by` INT NOT NULL,
  `is_picked` TINYINT(1) NOT NULL DEFAULT 0,
  `is_draw` TINYINT(1) NOT NULL DEFAULT 0,
  `is_flushed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'cards have been flushed back to stack',
  PRIMARY KEY (`card_round_id`),
  INDEX `fk_card_round_cards1_idx` (`card_id` ASC),
  INDEX `fk_card_round_rounds1_idx` (`round_id` ASC),
  INDEX `fk_cards_in_round_player1_idx` (`drawn_by` ASC),
  INDEX `cards_in_round_misc_INDEX` (`is_picked` ASC, `is_draw` ASC, `is_flushed` ASC),
  CONSTRAINT `fk_card_round_cards1`
    FOREIGN KEY (`card_id`)
    REFERENCES `wargame`.`card` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_round_rounds1`
    FOREIGN KEY (`round_id`)
    REFERENCES `wargame`.`round` (`round_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_in_round_player1`
    FOREIGN KEY (`drawn_by`)
    REFERENCES `wargame`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'log of which card was picked';


-- -----------------------------------------------------
-- Table `wargame`.`stack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`stack` (
  `stack_id` INT NOT NULL,
  `stack_owner` INT NOT NULL COMMENT 'player_session_id',
  `stack_height` INT NOT NULL DEFAULT 0 COMMENT 'game ends when a stack reaches zero',
  PRIMARY KEY (`stack_id`),
  INDEX `stack_misc_INDEX` (`stack_owner` ASC, `stack_height` ASC),
  CONSTRAINT `fk_stack_player_session1`
    FOREIGN KEY (`stack_owner`)
    REFERENCES `wargame`.`player_session` (`player_session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wargame`.`cards_in_stack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wargame`.`cards_in_stack` (
  `card_stack_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `card_id` INT NOT NULL,
  `stack_id` INT NOT NULL,
  `is_popped` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'if 1 means no longer in stack',
  `pushed_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `popped_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`card_stack_id`),
  INDEX `fk_cards_in_stack_stack1_idx` (`stack_id` ASC),
  INDEX `fk_cards_in_stack_card1_idx` (`card_id` ASC),
  INDEX `card_in_stack_is_popped_INDEX` (`is_popped` ASC),
  CONSTRAINT `fk_cards_in_stack_stack1`
    FOREIGN KEY (`stack_id`)
    REFERENCES `wargame`.`stack` (`stack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_in_stack_card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `wargame`.`card` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'rolling stack';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
